config/routes.rb
Rails.application.routes.draw do
 root to: 'pages#home'
 devise_for :users, controllers: { registrations: 'users/registrations' }
 get 'contact-us', to: 'contacts#new'
 get 'about', to: 'pages#about'
 resources :contacts, only: :create
 get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
    has_many :users
    
attr_accessor :stripe_card_token
def save_with_subscription
  if valid?
    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    self.stripe_customer_token = customer.id
    save!
  end
end
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


before_action :configure_permitted_parameters, if: :devise_controller?
protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    
    # GET request to /contact-us
    # Show new contact form 
    def new
        @contact = Contact.new
    end
    
    # POST request /contacts
    def create
        # Mass assignment of form fields into contact object
        @contact = Contact.new(contact_params)
        # Save the contact object to database
        if @contact.save
            # Store form fields via parameters, into variables
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            # Plug variables into Contact mailer email method
            ContactMailer.contact_email(name, email, body).deliver
            
            flash[:success] = "Message Sent."
            # Store success message in flash field
            # and redirect to new action
            redirect_to new_contact_path
        else
            flash[:danger] = @contact.errors.full_messages.join(", ")
            redirect_to new_contact_path
        end
    end
private
    def contact_params
        params.require(:contact).permit(:name, :email, :comments)
    end
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
end

private
  def select_plan
    unless (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class='container'>
    <div class="row">
        <h3 class="text-center">Contact US</h3>
        <div class="col-md-4 col-md-offset-4">
            <div class='well'>
                <%= form_for @contact do |f| %>
                   <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'form-control' %>
                   </div>
                    <div class="form-group">
                        <%= f.label :email %>
            
                        <%= f.text_field :email, class: 'form-control' %>
                    </div>
                    <div class="form-group">
                        <%= f.label :comments %>
                        <%= f.text_area :comments, class: 'form-control' %>
                   </div>
                    <%= f.submit 'Submit', class: 'btn btn-default' %>
              <% end %>
          </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevMatch</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class='container'>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fa fa-group"></i>
          DevMatch
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        <div class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-primary navbar-btn" %>
        <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About", about_path%></li>
          <li><%= link_to "Contact Us", contact_us_path%></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>
  <div class="container flash-container">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>
  </div>
  <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container text-center">
    <h1>About Page</h1>
    <p>We are DevMatch. Our company focuses on creating an exclusive community
    for developers and entrepreneurs to meet and collaborate. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, delectus, deleniti,
    ad cum illo dicta et quisquam quae commodi libero vel ex accusamus. Vitae amet voluptatibus repellat deserunt rem illo!
    </p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-left container-fluid">
    <h1>Welcome to DevMatch</h1>
    <h3>A membership site where entrepreneurs can meet developers</h3>
</div>

<br>

<div class= "container extra-information">
    <div class="row middle-row">
        <div class="col-md-4">
            <div class="container-fluid info-panel">
               <img src="https://assets-cdn.github.com/images/modules/site/home-ill-work.png?sn" alt="portrait" align="middle">
               <br>
               <h4 align="center">Connect with the <br>professionals in your area!</h4>
               <p align="center">DevMatch helps you connect to the people you need to jumpstart your business' online presence. All developers are verified by our team.</p>
            </div>
        </div>
        <div class="col-md-4">
           <div class="container-fluid info-panel">
               <img src="https://assets-cdn.github.com/images/modules/site/home-ill-build.png?sn" alt="portrait" align="middle">
               <br>
               <h4 align="center">Discuss your business' needs with<br>developers that know your customers!</h4>
               <p align="center">DevMatch helps you connect to the people you need to jumpstart your business' online presence. All developers are verified by our team.</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="container-fluid info-panel">
               <img src="https://assets-cdn.github.com/images/modules/site/home-ill-projects.png?sn" alt="portrait" align="middle">
               <br>
               <h4 align="center">Learn to program yourself!<br>DevMatch can match you with tutors!</h4>
               <p align="center">DevMatch helps you connect to the people you need to jumpstart your business' online presence. All developers are verified by our team.</p>
            </div>
        </div>
    </div>
</div>

<br>
<div class="container testimonials">
    <h2 class="text-center">Our customer's satisfaction speaks for itself!</h2>
    <div class="row">
        <div class= "col-md-4">
        
        </div>
        <div class= "col-md-4">
        
        </div>
        <div class= "col-md-4">
        
        </div>
    </div>
</div>


<div class="container home-signup-links">
    <div class="row">
        <div class="col-md-6">
            <div class="well division">
                <div class="container-fluid">
                    <h2 class="text-center">Basic Membership</h2>
                    <h4 class="text-center">Sign up for free to get instant access to the community. See what's out there!</h4>
                </div>
                <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
            </div>
        </div>
        <div class="col-md-6">
        <div class="well division">
            <div class="container-fluid">
                <h2 class="text-center">Pro Membership</h2>
                <h4 class="text-center">Sign up for the pro account for 10$/month to get access to the community and contact information!</h4>
            </div>
            <%= link_to "Sign Up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
        </div>
    </div>
</div>


<br>
<hr class="social-media-divider">
<ul>
    <li class="copyright"><i class="fa fa-copyright"></i> 2016 DevMatch Inc.</li>
    <li class="social-media-bar">
        <ul>
            <li class="social-media"><a href="http://facebook.com"> <i class="fa fa-facebook social-icon"></i></a></li>
            <li class="social-media"><a href="twitter.com"> <i class="fa fa-twitter social-icon"></i></a></li>
            <li class="social-media"><a href="googleplus.com"> <i class="fa fa-linkedin social-icon"></i></a></li>
            <li class="social-media"></li></li><a href="linkedin.com"> <i class="fa fa-google-plus social-icon"></i></a></li>
        </ul>
    </li>
</ul>